version: '3.9'

services:
  flightsAPI:
    container_name: flightsAPI
    image: flightsAPI
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '8080:8080'
